import React from "react";
import { ArrowUpRight } from "lucide-react";

const BACKEND = process.env.REACT_APP_BACKEND_URL;

export const SampleGallery = ({ dataset, onPick, busy }) => {
    if (!dataset) return null;
    const samples = dataset.samples || [];
    return (
        <section
            id="gallery"
            data-testid="gallery-section"
            className="border-b hairline"
        >
            <div className="max-w-[1440px] mx-auto px-6 md:px-10 lg:px-14 py-14 md:py-20">
                <div className="grid grid-cols-12 gap-6 md:gap-10 mb-10">
                    <div className="col-span-12 lg:col-span-3">
                        <div className="text-[10px] uppercase tracking-[0.3em] font-mono text-black/50 mb-3">
                            04 / Reference set
                        </div>
                        <h2 className="font-display font-bold text-3xl md:text-4xl tracking-tight leading-[1]">
                            Or pick a&nbsp;sample.
                        </h2>
                        <div className="mt-3 text-[11px] font-mono uppercase tracking-[0.2em] text-black/55">
                            {dataset.name}
                        </div>
                    </div>
                    <div className="col-span-12 lg:col-span-7 lg:col-start-6">
                        <p className="text-sm font-mono text-black/70 leading-relaxed">
                            One synthetic exemplar per class is generated by
                            the backend (no remote CDN, no broken images).
                            Clicking pushes it through the same CNN +
                            doctor-report pipeline.
                        </p>
                    </div>
                </div>

                <div
                    className={`grid grid-cols-2 ${
                        samples.length === 3 ? "lg:grid-cols-3" : "lg:grid-cols-4"
                    } gap-0 border border-black/15`}
                >
                    {samples.map((s, idx) => (
                        <button
                            key={s.id}
                            type="button"
                            onClick={() => !busy && onPick(s)}
                            data-testid={`sample-${dataset.id}-${s.class_id}`}
                            disabled={busy}
                            className={`group relative text-left bg-white hover:bg-paper-3 transition-colors disabled:opacity-50 ${
                                idx > 0 ? "lg:border-l border-black/10" : ""
                            } ${idx >= 2 ? "border-t lg:border-t-0" : ""} ${idx === 1 ? "border-l" : ""}`}
                        >
                            <div className="aspect-square bg-black overflow-hidden relative">
                                <img
                                    src={`${BACKEND}${s.image_url}`}
                                    alt={s.label}
                                    data-testid={`sample-img-${s.id}`}
                                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500 ease-out"
                                />
                                <div className="absolute top-2 left-2 right-2 flex items-center justify-between text-[9px] uppercase tracking-[0.3em] font-mono text-white/70">
                                    <span>// class {String(idx + 1).padStart(2, "0")}</span>
                                    <span>{dataset.modality}</span>
                                </div>
                            </div>
                            <div className="p-5 flex items-start justify-between gap-3">
                                <div>
                                    <div className="text-[10px] uppercase tracking-[0.28em] font-mono text-black/50">
                                        {dataset.body_part}
                                    </div>
                                    <div className="font-display font-bold text-xl tracking-tight mt-1">
                                        {s.label}
                                    </div>
                                </div>
                                <ArrowUpRight className="w-5 h-5 mt-1 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
                            </div>
                        </button>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default SampleGallery;
